nodes:
  data:
    node_builder: ...
    attributes:
      weights:
        _target_: anemoi.graphs.nodes.attributes.IsolatitudeAreaWeights
        norm: unit-max # options: unit-max, unit-sum, unit-std
  hidden: ...
