defaults:
  - data: zarr
  - dataloader: native_grid
  - diagnostics: evaluation
  - hardware: example
  - graph: encoder_decoder_only
  - model: transformer_ens
  - training: default
  - _self_

config_validation: True

# Changes in hardware
hardware:
  files:
    truncation: ${data.resolution}-O32-linear.mat.npz
    truncation_inv: O32-${data.resolution}-linear.mat.npz
  num_gpus_per_ensemble: 1
  num_gpus_per_node: 1
  num_nodes: 1
  num_gpus_per_model: 1

# Changes in datamodule
datamodule:
  _target_: anemoi.training.data.datamodule.AnemoiEnsDatasetsDataModule

data:
  resolution: o96

# Changes in training
training:
  model_task: anemoi.training.train.tasks.GraphEnsForecaster
  ensemble_size_per_device: 4
  max_epochs: 20

  # Changes in strategy
  strategy:
    _target_: anemoi.training.distributed.strategy.DDPEnsGroupStrategy
    num_gpus_per_ensemble: ${hardware.num_gpus_per_ensemble}
    num_gpus_per_model: ${hardware.num_gpus_per_model}

  # Changes in training loss
  training_loss:
    _target_: anemoi.training.losses.kcrps.AlmostFairKernelCRPS
    scalars: ['variable']
    ignore_nans: False
    alpha: 1.0

  # Changes in validation metrics
  validation_metrics:
    - _target_: anemoi.training.losses.kcrps.AlmostFairKernelCRPS
      scalars: []
      ignore_nans: False
      alpha: 1.0

diagnostics:
  plot:
    callbacks: []
